// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHzWdYAE19BPVqml5vrUgaA7h_kKn0cl4',
    appId: '1:1096621663325:android:705916de5c784691e359b4',
    messagingSenderId: '1096621663325',
    projectId: 'kpop-on-4e17a',
    databaseURL: 'https://kpop-on-4e17a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpop-on-4e17a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2FJgywWX5wEdrBOuhFx2w9kIWL0p6Y_w',
    appId: '1:1096621663325:ios:91295782c43c4d8ce359b4',
    messagingSenderId: '1096621663325',
    projectId: 'kpop-on-4e17a',
    databaseURL: 'https://kpop-on-4e17a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kpop-on-4e17a.appspot.com',
    androidClientId: '1096621663325-9pfb18of2vg6pnmfso84gvph26nila4g.apps.googleusercontent.com',
    iosClientId: '1096621663325-req7uqufimltkven74qapgq0fnq75aoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kpopOnYoutube',
  );
}
